README.md

Hello, I'm from the ChainX team. We're actually aiming to be a cross-chain asset management platform on Substrate, not a social network :(.

Correct ChainX intro

---

README.md

worth listening if you want to know more about Trust wormholes and getting familiar with glossary around Polkadot ecosystem

Added ZeroKnowledge Episode #83 about SPREE

---

README.md
README_CN.md

Add [PolkaWorld](https://www.polkaworld.org/)

Add PolkaWorld

---

README.md

add encointer.org

---

README.md

adding substrate-api-client

---

README.md

Adds links about Substrate Collaborative Learning to the awesome list.

Add SCL and remove Events

---

README.md

Remove dead IPFS link

---

README.md
README_CN.md

Small changes in projects list

---

README.md
contributing.md

Clean lint

---

README.md

Add remote build guide

---

README.md

Add SubstrateNetApi

---

README.md

I noticed there were still some issues brought up when merging our list into the main Awesome repo, so I made some changes to address them. 
Original issue: #22

Fix: Readme issues

---

README.md

included my script in the list of ecosystem tools. Thanks for reaching out, Dan.

included staking-rewards-collector

---

README.md

c.f. https://stackoverflow.com/questions/64550808/is-there-any-decentralized-cloud-project-compatible-with-polkadots-substrate/64550809?noredirect=1#comment114154508_64550809

Add Decentralized Cloud Projects section

---

README.md

https://www.shawntabrizi.com/substrate-js-utilities/

Add shawntabrizi substrate js utils

---

README.md

Add Polkadot Wiki tools

---

README.md

https://polkaview.network/dot Shows historical data, by eras, on minimum staked to be rewarded.

Adding PolkaView to Comunnity Resources

---

README.md

From FRAME v2 seminar mention:
https://youtu.be/5pLHzKMCEtg?t=4957

add subsee

---

README.md

close #45 in favor of minor wordings update

Wordings update over PR#45

---

README.md

Source coming from https://github.com/paritytech/substrate-open-working-groups/discussions/16#discussion-3286416

Updated with Substrate mobile tool

---

.github/workflows/main.yml

add awesome-lint to github actions

---

README.md

Add runtime metrics exporter by @kianenigma

Add runtime metrics exporter

---

README.md

updated new Knowledge Base link

---

README.md

Migrated from https://github.com/substrate-developer-hub/substrate-docs/issues/114

add a few ss58 related items

---

README.md

polkadot-scripts

---

README.md

Adding Subsquid as a tool for Substrate

Added Subsquid entry

---

README.md

For additional info please see https://github.com/substrate-developer-hub/substrate-docs/pull/1037

Add Soramitsu's SCALE codec JS implementation

---

README.md

found here: https://substrate.stackexchange.com/questions/3263/why-is-app-crypto-not-building-in-frame-system-runtime

substrate-toml-lint

---

README.md

https://github.com/rmrk-team/rmrk-substrate

add rmrk-pallets

---

README.md

Resolves paritytech/parity-scale-codec-ts#16

Add `parity-scale-codec-ts`

---

README.md

Close https://github.com/hack-ink/subalfred/issues/84.
cc @NukeManDan

Add `subalfred`

---

README.md

updated the repository to match newest Substrate API
added new Toolchain/SDK for Substrate

Updated repos.

---

README.md

Impressive feature list https://polkaholic.io/features

Add polkaholic.io to tools

---

README.md

These tools are both officially maintained and complement tools like Subxt for working with encoded values.

Add scale-value/scale-decode to tools list

---

README.md

Add's the metadata portal webpage maintained by Nova Wallet.

Add new tool

---

README.md

#101 passes lint, thanks @wottpal !

Add references to INK!athon & useInkathon
